project:
  type: website
  render:
    - "*.qmd"
    - "*.ipynb"
    - "!*_L-slides_*.ipynb"
    
theme:
    light: flatly
    dark: darkly

format:    
  html:    
    code-overflow: wrap
    toc: true
    self-contained: true
    # standalone: true
    embed-resources: true
    toc-depth: 3
    code-block-border-left: "#31BAE9"
    code-block-bg: true    
    #    highlight-style: pygments
 #   highlight-style: github
 #   include-in-header:
 #     - text: |
 #         <style>
 #         .cell-output-stdout code {
 #           word-break: break-wor !important;
 #           white-space: pre-wrap !important;
 #         }
 #         </style>      

    #  typst:
    # toc: true
    # section-numbering: 1.1.a
    # columns: 1
    # papersize: a4 

  epub: default

  pdf:
    papersize: a4


