project:
  type: website
  render:
    - "index.qmd" 
    - "*.ipynb" 
    - "*.qmd" 
    - "!*_L-slides_*.ipynb"
    - "!HIDDEN"
  resources:
    resources

notebook-links: false

theme:
  light: flatly
  dark: darkly

format:    
  html:    
    code-overflow: wrap
    toc: true
    toc-depth: 3
    toc-location: left
    self-contained: true
    embed-resources: true
    code-block-border-left: "#31BAE9"
    code-block-bg: true    
    highlight-style: github
    number-sections: false
    anchor-sections: true
    footnotes-hover: true
    search: true   
    smooth-scroll: true
    section-divs: true
    include-in-header:
      - text: |
          <style>
          .cell-output-stdout code {
            word-break: break-word !important;
            white-space: pre-wrap !important;
          }
          </style>

#  pdf:
#    documentclass: scrartcl
#    papersize: a4
#    number-sections: true
#    colorlinks: true
#    mainfont: LiberationSerif
#    monofont: LiberationMono
#    include-in-header:
#      text: |
#        \usepackage{fvextra}
#        \DefineVerbatimEnvironment{Highlighting}{Verbatim}{breaklines,commandchars=\\\{\}}
#        \DefineVerbatimEnvironment{OutputCode}{Verbatim}{breaklines,commandchars=\\\{\}}
#        \usepackage{fancyhdr}
#        \pagestyle{fancy}

website:
  navbar:
    background: primary
    search: true
  sidebar:
    style: docked
    contents: auto
  comments: 
    utterances:
      repo: ebpro/utterances
    