project:
  output-dir: _output/_slides
  render:
    - "index.qmd" 
    - "*_L_*.ipynb"  
    - "*_L_*.qmd"  
post-render: quarto-utils/_utils/post-render.sh

format:

  revealjs:
    # chalkboard: true
    footer: E. Bruno
    slide-level: 3
    navigation-mode: vertical
    slide-number: c/t
    smaller: true
    embed-resources: true
    # theme: [league, custom.scss]
    # theme: [dark, quarto-utils/custom.scss]
    #theme: [white, quarto-utils/custom.scss]
    theme: [white, quarto-utils/custom.scss]
    #theme: moon
    highlight-style: github
    code-overflow: wrap
    code-block-bg: true
    #code-block-border-left: "#31BAE9"
    multiplex: true
    transition: slide
    progress: true
    scrollable: true

#  beamer: 
#    navigation: horizontal
#    aspectratio: 169
#    classoption: ['notheorems']
#    theme: Frankfurt
#    papersize: a4
#    shift-heading-level-by: -1
#    include-in-header: 
#      text: |
#          \usepackage{fvextra}
#          \DefineVerbatimEnvironment{Highlighting}{Verbatim}{breaklines,commandchars=\\\{\}}         
#          \setbeamertemplate{navigation symbols}{}
#          \setbeamertemplate{footline}[page number]
#
#          \usepackage{fontspec} 
#          \defaultfontfeatures{Mapping=tex-text} 

#    include-before-body:
#      text: |
#        \RecustomVerbatimEnvironment{verbatim}{Verbatim}{
#          showspaces = false,
#          showtabs = false,
#          breaksymbolleft={},
#          breaklines
#        }  
        
revealjs-plugins:
  - verticator
