project:
  output-dir: _output/_slides
  render:
    - "index.qmd" 
    - "*_L_*.ipynb"
    - "*_L_*.qmd"
    - "*_P_*.qmd"
    - "*_P_*.ipynb"
    - "!HIDDEN"
  post-render: ./quarto-utils/_utils/post-render.sh

format:

  revealjs:
    # Presentation settings
    theme: [white, quarto-utils/custom.scss]
    highlight-style: github
    footer: "E. Bruno - {{< meta title >}}"
    slide-level: 3
    navigation-mode: vertical
    slide-number: c/t

    # Code display
    code-overflow: wrap
    code-block-bg: true
    code-copy: true
    code-line-numbers: true

    # Features
    multiplex: true
    transition: slide
    progress: true
    scrollable: true
    preview-links: true

    # Controls
    controls: true
    controls-layout: bottom-right

    # Plugins
    chalkboard: 
      enabled: true
      buttons: true
    
    # PDF Export
    pdf-separate-fragments: true
    
    # Performance
    # embed-resources: true
    smaller: true

revealjs-plugins:
  - verticator
