project:
  type: website
  render:
    - "*.qmd"
    - "*.ipynb"
    - "!*_L-slides_*.ipynb"

notebook-links: false

theme:
    light: flatly
    dark: darkly

format:    
  html:    
    code-overflow: wrap
    toc: true
    self-contained: true
    embed-resources: true
    toc-depth: 3
    code-block-border-left: "#31BAE9"
    code-block-bg: true    
    highlight-style: github
 #   include-in-header:
 #     - text: |
 #         <style>
 #         .cell-output-stdout code {
 #           word-break: break-wor !important;
 #           white-space: pre-wrap !important;
 #         }
 #         </style>      

# epub: default

  pdf:
      number-sections: true
      mainfont: LiberationSerif
      monofont: LiberationMono
      papersize: A4
      documentclass: scrartcl
      shift-heading-level-by: -1
      link-citations: true
      linkcolor: blue
      include-in-header:
        text: |
            \usepackage{fvextra}
            \DefineVerbatimEnvironment{Highlighting}{Verbatim}{breaklines,commandchars=\\\{\}}
            \DefineVerbatimEnvironment{OutputCode}{Verbatim}{breaklines,commandchars=\\\{\}}
            \usepackage{fancyhdr}
            \pagestyle{fancy}
            % \fancyhf{}
            % \fancyfoot[C]{\thepage}
      include-before-body:
        text: |
          \RecustomVerbatimEnvironment{verbatim}{Verbatim}{
            showspaces = false,
            showtabs = false,
            breaksymbolleft={},
            breaklines
          }
